services:
  db:
    image: postgres:17-alpine
    container_name: gzlaeo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gzlaeo_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: gzlaeo-adminer
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
